name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_lint:
        description: 'Executar lint?'
        required: false
        default: true
        type: boolean
      run_tests:
        description: 'Executar testes?'
        required: false
        default: true
        type: boolean

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_lint: ${{ inputs.run_lint }}
      run_tests: ${{ inputs.run_tests }}

  package:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gerar .jar do projeto
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: [lint-and-test, package]
    steps:
      - name: Mensagem de deploy
        run: echo "Deploy realizado com sucesso"
