name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir variáveis não sensíveis
        run: |
          echo "Modo da aplicação: ${{ vars.APP_MODE }}"
          echo "E-mail de suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Usar segredo de forma segura
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          echo "Usando token secreto (não exibido nos logs)"
          echo "Autenticando com o token: ${TOKEN:0:4}********"
