name: issue-on-failure

on: workflow_dispatch

permissions:
  issues: write

jobs:
  check-and-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar variável obrigatória
        id: check
        run: |
          if [ -z "${{ secrets.DEPLOY_SECRET }}" ]; then
            echo "::set-output name=fail::true"
          else
            echo "::set-output name=fail::false"
          fi

      - name: Criar issue se DEPLOY_SECRET estiver ausente
        if: steps.check.outputs.fail == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Deploy falhou",
              "body": "A variável DEPLOY_SECRET está ausente nos secrets. Verifique as configurações."
            }'