name: Teste Runner Auto-Hospedado

on:
  push:
    branches:
      - main

jobs:
  run-local:
    runs-on: self-hosted
    steps:
      - name: Mostrar informações do sistema
        run: uname -a
        shell: bash

      - name: Mostrar versão do Java
        run: java -version
        shell: bash

      - name: Instalar 7zip via Chocolatey
        run: choco install 7zip -y
        shell: powershell
